# Data Preprocessing

In [1]:
import os, time, random
import numpy as np
import pandas as pd
import cv2, torch
from tqdm.auto import tqdm
import shutil as sh
from sklearn import preprocessing, model_selection

from IPython.display import Image, clear_output
import matplotlib.pyplot as plt
from PIL import Image
%matplotlib inline

In [2]:
img_path = 'datasets/TrainImages/'
shapes = []
for img in tqdm(os.listdir(img_path)):
    my_img = cv2.imread(img_path+img)
    shapes.append(my_img.shape)
print(set(shapes))
img_w = 1000
img_h = 1000

  0%|          | 0/660 [00:00<?, ?it/s]

{(1000, 1000, 3)}

- Train

In [3]:
source_lable_path = 'datasets/TrainGroundTruth/'
destination_lable_path = 'labels/'


read_list = []
for lable in tqdm(os.listdir(source_lable_path)):
    with open(source_lable_path+lable, "r") as txt_file:
        xmin,ymin,xmax,ymax = [float(i) for i in txt_file.readlines()[0][:-1].split(',')]
        read_list.append([lable[:-4],xmin,ymin,xmax,ymax])
        
df = pd.DataFrame(read_list,columns=['name','xmin','ymin','xmax','ymax'])
df

  0%|          | 0/660 [00:00<?, ?it/s]

    name   xmin   ymin   xmax   ymax
0      1  509.0  847.0  938.0  903.0
1     10  422.0  662.0  740.0  715.0
2    100  429.0  669.0  551.0  700.0
3    101  532.0  262.0  842.0  320.0
4    102   11.0  736.0  366.0  804.0
..   ...    ...    ...    ...    ...
655   95  462.0  617.0  789.0  707.0
656   96  543.0  793.0  600.0  834.0
657   97   59.0  713.0  432.0  787.0
658   98  394.0  634.0  505.0  704.0
659   99  172.0  626.0  570.0  682.0

[660 rows x 5 columns]

In [4]:
df['x_center'] = (df['xmin'] + df['xmax'])/2
df['y_center'] = (df['ymin'] + df['ymax'])/2
df['w'] = df['xmax'] - df['xmin']
df['h'] = df['ymax'] - df['ymin']
df['labels'] = 0
df['x_center_norm'] = df['x_center']/img_w
df['y_center_norm'] = df['y_center']/img_h
df['w_norm'] = df['w']/img_w
df['h_norm'] = df['h']/img_h
df

,name,xmin,ymin,xmax,ymax,x_center,y_center,w,h,labels,x_center_norm,y_center_norm,w_norm,h_norm
0,1,509.0,847.0,938.0,903.0,723.5,875.0,429.0,56.0,0,0.7235,0.8750,0.429,0.056
1,10,422.0,662.0,740.0,715.0,581.0,688.5,318.0,53.0,0,0.5810,0.6885,0.318,0.053
2,100,429.0,669.0,551.0,700.0,490.0,684.5,122.0,31.0,0,0.4900,0.6845,0.122,0.031
3,101,532.0,262.0,842.0,320.0,687.0,291.0,310.0,58.0,0,0.6870,0.2910,0.310,0.058
4,102,11.0,736.0,366.0,804.0,188.5,770.0,355.0,68.0,0,0.1885,0.7700,0.355,0.068
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
655,95,462.0,617.0,789.0,707.0,625.5,662.0,327.0,90.0,0,0.6255,0.6620,0.327,0.090
656,96,543.0,793.0,600.0,834.0,571.5,813.5,57.0,41.0,0,0.5715,0.8135,0.057,0.041
657,97,59.0,713.0,432.0,787.0,245.5,750.0,373.0,74.0,0,0.2455,0.7500,0.373,0.074
658,98,394.0,634.0,505.0,704.0,449.5,669.0,111.0,70.0,0,0.4495,0.6690,0.111,0.070
659,99,172.0,626.0,570.0,682.0,371.0,654.0,398.0,56.0,0,0.3710,0.6540,0.398,0.056

In [5]:
df_train, df_valid = model_selection.train_test_split(df, test_size=0.1, random_state=13, shuffle=True)
print(df_train.shape, df_valid.shape)

(594, 14) (66, 14)

In [6]:
source_img_path = 'datasets/TrainImages/'
destination_img_path = 'datasets/signature/images/train/'
destination_img_path_val = 'datasets/signature/images/val/'
train_label_path = 'datasets/signature/labels/train/'
val_label_path = 'datasets/signature/labels/val/'
for img in tqdm(os.listdir(source_img_path)):
    row = df_train[df_train['name'] == img.split('.')[0]][['labels', 'x_center_norm', 'y_center_norm', 'w_norm', 'h_norm']]
    if len(row):
        sh.copy(source_img_path+img, destination_img_path+img)
        np.savetxt(train_label_path+str(img.split('.')[0])+'.txt',np.array(row),fmt=["%d", "%f", "%f", "%f", "%f"])   
    row = df_valid[df_valid['name'] == img.split('.')[0]][['labels', 'x_center_norm', 'y_center_norm', 'w_norm', 'h_norm']]
    if len(row):
        sh.copy(source_img_path+img, destination_img_path_val+img)
        np.savetxt(val_label_path+str(img.split('.')[0])+'.txt',np.array(row),fmt=["%d", "%f", "%f", "%f", "%f"])

  0%|          | 0/660 [00:00<?, ?it/s]

In [7]:
source_lable_path = 'datasets/TestGroundTruth/'
destination_lable_path = 'labels/'

read_list = []
for lable in tqdm(os.listdir(source_lable_path)):
    with open(source_lable_path+lable, "r") as txt_file:
        xmin,ymin,xmax,ymax = [float(i) for i in txt_file.readlines()[0][:-1].split(',')]
        read_list.append([lable[:-4],xmin,ymin,xmax,ymax])
        
df = pd.DataFrame(read_list,columns=['name','xmin','ymin','xmax','ymax'])
df

  0%|          | 0/115 [00:00<?, ?it/s]

    name   xmin   ymin   xmax   ymax
0    680  493.0  692.0  698.0  742.0
1    681  138.0  684.0  275.0  714.0
2    682  534.0  465.0  738.0  506.0
3    683  622.0  553.0  771.0  599.0
4    684  442.0  594.0  674.0  674.0
..   ...    ...    ...    ...    ...
110  796  528.0  285.0  754.0  338.0
111  797  532.0  436.0  847.0  495.0
112  798  557.0  680.0  764.0  754.0
113  799  533.0  322.0  760.0  374.0
114  800  131.0  607.0  384.0  649.0

[115 rows x 5 columns]

In [8]:
df['x_center'] = (df['xmin'] + df['xmax'])/2
df['y_center'] = (df['ymin'] + df['ymax'])/2
df['w'] = df['xmax'] - df['xmin']
df['h'] = df['ymax'] - df['ymin']
df['labels'] = 0
df['x_center_norm'] = df['x_center']/img_w
df['y_center_norm'] = df['y_center']/img_h
df['w_norm'] = df['w']/img_w
df['h_norm'] = df['h']/img_h
df

,name,xmin,ymin,xmax,ymax,x_center,y_center,w,h,labels,x_center_norm,y_center_norm,w_norm,h_norm
0,680,493.0,692.0,698.0,742.0,595.5,717.0,205.0,50.0,0,0.5955,0.7170,0.205,0.050
1,681,138.0,684.0,275.0,714.0,206.5,699.0,137.0,30.0,0,0.2065,0.6990,0.137,0.030
2,682,534.0,465.0,738.0,506.0,636.0,485.5,204.0,41.0,0,0.6360,0.4855,0.204,0.041
3,683,622.0,553.0,771.0,599.0,696.5,576.0,149.0,46.0,0,0.6965,0.5760,0.149,0.046
4,684,442.0,594.0,674.0,674.0,558.0,634.0,232.0,80.0,0,0.5580,0.6340,0.232,0.080
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110,796,528.0,285.0,754.0,338.0,641.0,311.5,226.0,53.0,0,0.6410,0.3115,0.226,0.053
111,797,532.0,436.0,847.0,495.0,689.5,465.5,315.0,59.0,0,0.6895,0.4655,0.315,0.059
112,798,557.0,680.0,764.0,754.0,660.5,717.0,207.0,74.0,0,0.6605,0.7170,0.207,0.074
113,799,533.0,322.0,760.0,374.0,646.5,348.0,227.0,52.0,0,0.6465,0.3480,0.227,0.052
114,800,131.0,607.0,384.0,649.0,257.5,628.0,253.0,42.0,0,0.2575,0.6280,0.253,0.042

In [9]:
source_img_path = 'datasets/TestImages/'
destination_img_path = 'datasets/signature/images/test/'
train_label_path = 'datasets/signature/labels/test/'
for img in tqdm(os.listdir(source_img_path)):
    row = df[df['name'] == img.split('.')[0]][['labels', 'x_center_norm', 'y_center_norm', 'w_norm', 'h_norm']]
    if len(row):
        sh.copy(source_img_path+img, destination_img_path+img)
        np.savetxt(train_label_path+str(img.split('.')[0])+'.txt',np.array(row),fmt=["%d", "%f", "%f", "%f", "%f"])

  0%|          | 0/115 [00:00<?, ?it/s]